[theme]
primaryColor = "#ff6b6b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
headless = true
port = $PORT
enableCORS = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[logger]
level = "info"
